### ISSUE TITLE
How to install apk-thumbnailer?

### ISSUE THREAD

**Issue by ghost** [theredbaron1834/Scripts#4]
Can you please tell me how to install the script, step by step?

**Comment by theredbaron1834** [comment]
Wow, sorry I never noticed this. I kind of just dump stuff I use up here, never had a "issue" before, so just missed it.

If you still want the info.


First you need to make sure you have a working version of aapt, a program to work with apks. It is a part of build-tools for android. I just installed the full sdk, as I want adb, etc, but you can do whatever. However, if aapt is in a different area, you will have to edit the code ( run which aapt once installed, and edit to fit). It is written for my arch linux install, and I don't know where other distro's store their aapt.

Then just run the following 2 commands (taken from my pkgbuild for it):


1st command creates the thumbnailer file, which your file manager will use to get a thumbnailer.
"echo "[Thumbnailer Entry]
TryExec=/usr/bin/apk-thumbnailer
Exec=/usr/bin/apk-thumbnailer %u %o
MimeType=application/vnd.android.package-archive" > /usr/share/thumbnailers/apk-thumbnailer.thumbnailer"



2nd command adds the thumbnailer "code" to your path, allowing the thumbnailer to exe it.
"echo "#!/bin/bash
file=\$(echo "\$1" | sed s'/file:\/\///g' | sed s'/%20/ /g' | sed s'/%5B/\[/g'| sed s'/%5D/\]/g') # Clean up thumbnailer for aapt
icon=\$(/opt/android-sdk/build-tools/*/aapt d --values badging "\$file" | grep application-icon- | sed s'/:/\n/g' | tail -n 1 | tr -d \') #Grab icon location
mkdir /tmp/apkthumbnailer/
cd /tmp/apkthumbnailer/
unzip -o "\$file" "\$icon" # Extract icon
convert -thumbnail 200 /tmp/apkthumbnailer/\$icon "\$2" # Make thumbnail" > /usr/bin/apk-thumbnailer"

Then just restart your file manager (it needs a full reset, which often means killing it, or a computer reset, and fm's often control the desktop, and just exiting out won't cut it".

Hope this helps, as as far as I know this is the only APK thumbnailer for none KDE desktops.

**Comment by alekcacko** [comment]
Well that was pretty good explanation.

Thank you. I figured it out way before but it's okay, this is very good explanation. You can edit the README 
:+1:

**Comment by theredbaron1834** [comment]
Not really good at readme's, as I am sure you noticed.

So I added an installer and some help to it. Now you just have to run as root, and you are done. (well, aside from the aapt stuff, going to look into making that easier soon too though)

**Comment by alekcacko** [comment]
Well, for Ubuntu aapt is available on the official repository so it shouldn't be hard for me. aapt might be in the AUR for Arch as well.

**Comment by theredbaron1834** [comment]
The problem is, for arch anyways, that the package is installed to /opt, and not added to your path by default, hince my crappy hack to get it to work.  I am going to have to a loop I guess, checking for it with which aapt, as well as looking in opt. That is my next free time project.
